AWSTemplateFormatVersion: "2010-09-09"
Description: "EFS pour MapServer avec mount targets dans 2 subnets privés"

Resources:
  # ---------------------------
  #  File System EFS
  # ---------------------------
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      PerformanceMode: generalPurpose
      ThroughputMode: bursting
      FileSystemTags:
        - Key: Name
          Value: efs-mapserver

  # ---------------------------
  #  Mount Target AZ A
  # ---------------------------
  MountTargetA:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !ImportValue vpc-mapserver-PrivateSubnetA
      SecurityGroups:
        - !ImportValue vpc-mapserver-EFSSG

  # ---------------------------
  #  Mount Target AZ B
  # ---------------------------
  MountTargetB:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref FileSystem
      SubnetId: !ImportValue vpc-mapserver-PrivateSubnetB
      SecurityGroups:
        - !ImportValue vpc-mapserver-EFSSG

Outputs:

  FileSystemId:
    Description: "ID du EFS"
    Value: !Ref FileSystem
    Export:
      Name: vpc-mapserver-FileSystemId