AWSTemplateFormatVersion: "2010-09-09"
Description: "Load Balancer + 2 Target Groups + 2 ASG"

Parameters:
  CertificateArn:
    Type: String
    Default: ""
    Description: ARN du certificat ACM pour HTTPS

  EnableHTTPS:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: Active ou désactive le listener HTTPS

  InstanceType:
    Type: String
    Default: t3.micro
 

Conditions:
  UseHTTPS: !Equals [!Ref EnableHTTPS, "true"]

Resources:

  ############################################
  # LOAD BALANCER
  ############################################

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: alb-mapserver
      Scheme: internet-facing
      Type: application
      Subnets:
        - !ImportValue vpc-mapserver-PublicSubnetA
        - !ImportValue vpc-mapserver-PublicSubnetB
      SecurityGroups:
        - !ImportValue vpc-mapserver-AlbSecurityGroupId
      LoadBalancerAttributes:
        - Key: routing.http.drop_invalid_header_fields.enabled
          Value: true

  ############################################
  # TARGET GROUPS
  ############################################

  TargetGroupPublic:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-public
      VpcId: !ImportValue vpc-mapserver-VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 20

  TargetGroupPrivate:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: tg-private
      VpcId: !ImportValue vpc-mapserver-VpcId
      Port: 80
      Protocol: HTTP
      TargetType: instance
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 20

  ############################################
  # LISTENERS
  ############################################

  ListenerHTTP1:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404

  ListenerRuleAppHtml:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ListenerHTTP1
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - /app.html
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupPublic

  ListenerRuleMapserv:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ListenerHTTP1
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values:
            - /cgi-bin/mapserv*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupPrivate
  
  ListenerHTTPS1:
    Condition: UseHTTPS
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !If [UseHTTPS, !Ref CertificateArn, !Ref AWS::NoValue]
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: 404

  ListenerRuleAppHtmlHTTPS:
    Condition: UseHTTPS
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ListenerHTTPS1
      Priority: 10
      Conditions:
        - Field: path-pattern
          Values:
            - "/app.html"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupPublic

  ListenerRuleMapservHTTPS:
    Condition: UseHTTPS
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ListenerHTTPS1
      Priority: 20
      Conditions:
        - Field: path-pattern
          Values:
            - "/cgi-bin/mapserv*"
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupPrivate

 

  ############################################
  # LAUNCH TEMPLATE
  ############################################

  LaunchTemplateApp:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lt-app
      LatestVersionNumber: 1
      LaunchTemplateData:
        ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}"
        InstanceType: !Ref InstanceType
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: false
            Groups:
              - !ImportValue vpc-mapserver-AlbAppSecurityGroupId
        UserData:
          Fn::Base64: 
            Fn::Sub: 
              - |
                #!/bin/bash
                set -e
                # --- app carto client ---
                apt-get update -y
                apt-get install -y apache2

                # --- Création du site web ---
                mkdir -p /var/www/html
                cat > /var/www/html/app.html << 'EOF'
                <!DOCTYPE html>
                <html>
                <head>
                  <meta charset="utf-8" />
                  <title>Leaflet + MapServer + Layers Control</title>
                  <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />
                  <style>
                    #map { height: 100vh; }
                  </style>
                </head>
                <body>

                <div id="map"></div>
                <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
                <script>

                // Carte en EPSG:4326
                var map = L.map('map').setView([20, 0], 2);

                // Fond OSM (optionnel)
                var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                    maxZoom: 19,
                    attribution: '© OpenStreetMap'
                }).addTo(map);

                // Couche WMS MapServer
                var countries = L.tileLayer.wms("http://${ALBDNS}/cgi-bin/mapserv", {
                    map: "/srv/nfs/mapfile/mapserver_quickstart.map",   // <-- adapte si besoin
                    layers: "countries",
                    format: "image/png",
                    transparent: true,
                    version: "1.1.1"
                }).addTo(map);

                // Contrôle des couches
                var baseMaps = {
                    "OpenStreetMap": osm
                };

                var overlayMaps = {
                    "Countries (MapServer)": countries
                };

                L.control.layers(baseMaps, overlayMaps, { collapsed: false }).addTo(map);

                </script>
                </body>
                </html>EOF


              - {
                  ALBDNS: !GetAtt ALB.DNSName
                }
 

  LaunchTemplateMapserver:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lt-mapserver
      LatestVersionNumber: 1
      LaunchTemplateData:
        ImageId: !Sub "{{resolve:ssm:/aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id}}"
        InstanceType: !Ref InstanceType
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: false
            Groups:
              - !ImportValue vpc-mapserver-MapserverSecurityGroupId
        UserData:
          Fn::Base64:
            Fn::Sub: 
              - |
                #!/bin/bash
                set -e

                # --- Mise à jour système ---
                apt-get update -y
                apt-get upgrade -y

                apt install -y nfs-common
                apt install -y apache2
                apt install -y cgi-mapserver mapserver-bin gdal-bin
                a2enmod cgi

                # --- Configuration Apache pour MapServer ---
                cat > /etc/apache2/conf-available/mapserver.conf << 'EOF'
                # MapServer Apache Configuration

                # Define an alias: requests to /cgi-bin/mapserv execute the mapserv program
                ScriptAlias /cgi-bin/mapserv /usr/lib/cgi-bin/mapserv

                # Configure the directory containing the mapserv executable
                <Directory /usr/lib/cgi-bin/>
                    Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                    AllowOverride None
                    Require all granted
                </Directory>

                # Optional: Set environment variables if needed (e.g., for PROJ data)
                # SetEnv PROJ_LIB /usr/share/proj/
                EOF

                a2enconf mapserver

                # --- AWS CloudFormation Helper Scripts ---
                #apt install -y heat-cfntools

                # --- Préparation du point de montage NFS ---
                mkdir -p /srv/nfs
                mount -t nfs4 -o nfsvers=4.1 ${EFS}.efs.${AWS::Region}.amazonaws.com:/ /srv/nfs

                echo "${EFS}.efs.${AWS::Region}.amazonaws.com:/ /srv/nfs nfs4 defaults,_netdev 0 0" >> /etc/fstab

                # --- Initialisation du contenu partagé ---
                if [ ! -f /srv/nfs/.initialized ]; then
                    mkdir -p /srv/nfs/data
                    mkdir -p /srv/nfs/mapfile

                    curl -o /srv/nfs/mapfile/mapserver_quickstart.map \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/mapfile/mapserver_quickstart.map

                    curl -o /srv/nfs/data/ne_110m_admin_0_countries.README.html \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/data/ne_110m_admin_0_countries.README.html

                    curl -o /srv/nfs/data/ne_110m_admin_0_countries.VERSION.txt \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/data/ne_110m_admin_0_countries.VERSION.txt

                    curl -o /srv/nfs/data/ne_110m_admin_0_countries.cpg \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/data/ne_110m_admin_0_countries.cpg

                    curl -o /srv/nfs/data/ne_110m_admin_0_countries.shp \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/data/ne_110m_admin_0_countries.shp

                    curl -o /srv/nfs/data/ne_110m_admin_0_countries.prj \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/data/ne_110m_admin_0_countries.prj

                    curl -o /srv/nfs/data/ne_110m_admin_0_countries.shx \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/data/ne_110m_admin_0_countries.shx

                    curl -o /srv/nfs/data/ne_110m_admin_0_countries.dbf \
                      https://raw.githubusercontent.com/chocho11/testmapserveraws/main/nfs/data/ne_110m_admin_0_countries.dbf

                    touch /srv/nfs/.initialized
                fi

                # --- Droits pour Apache ---
                chown -R www-data:www-data /srv/nfs
                chmod -R 755 /srv/nfs

                # --- Redémarrage final ---
                systemctl enable apache2
                systemctl restart apache2
              - {
                  EFS: !ImportValue vpc-mapserver-FileSystemId
                }




  ############################################
  # ASG PUBLIC
  ############################################

  ASGPublic:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !ImportValue vpc-mapserver-PublicSubnetA
        - !ImportValue vpc-mapserver-PublicSubnetB
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateApp
        Version: !GetAtt LaunchTemplateApp.LatestVersionNumber
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "2"
      TargetGroupARNs:
        - !Ref TargetGroupPublic
      Tags:
              - Key: Name
                Value: "MapServer-App-Frontend"  # Le nom que vous verrez dans la console EC2
                PropagateAtLaunch: true
  ScalingPolicyPublic:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref ASGPublic
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        TargetValue: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization

  ############################################
  # ASG PRIVATE
  ############################################

  ASGPrivate:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
         - !ImportValue vpc-mapserver-PrivateSubnetA
         - !ImportValue vpc-mapserver-PrivateSubnetB
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateMapserver
        Version: !GetAtt LaunchTemplateMapserver.LatestVersionNumber
      MinSize: "1"
      MaxSize: "3"
      DesiredCapacity: "2"
      TargetGroupARNs:
        - !Ref TargetGroupPrivate
      Tags:
              - Key: Name
                Value: "MapServer-Backend-Worker" # Le nom visible dans la console EC2
                PropagateAtLaunch: true
  ScalingPolicyPrivate:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref ASGPrivate
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        TargetValue: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization

Outputs:
  ALBArn:
    Value: !Ref ALB
    Export:
      Name: alb-mapserver-Arn

  TargetGroupPublicArn:
    Value: !Ref TargetGroupPublic
    Export:
      Name: tg-mapserver-public

  TargetGroupPrivateArn:
    Value: !Ref TargetGroupPrivate
    Export:
      Name: tg-mapserver-private