AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for MapServer infrastructure
Parameters:
  TemplateBucket:
    Type: String
    Description: Nom du bucket S3 contenant les templates CloudFormation
    
Resources:

  VPCStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/vpc.yml

  SGStack2:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/sg.yml
    DependsOn: VPCStack

  EFSStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/efs.yml
    DependsOn: SGStack

  ASGStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub https://${TemplateBucket}.s3.amazonaws.com/lb-asg-tg.yml
    DependsOn:
      - SGStack
      - EFSStack